"""Canonical OAuth scopes gtw needs, and Application Default Credentials helpers.

Single source of truth for the scopes this tool requires. Past incidents
adjusted scopes ad hoc (a string literal buried inside
TelemetryProvider._access_token, with the actionable fix only ever typed by
hand into a terminal), which drifted out of sync with what commands
actually need. Add a scope here once; `gtw auth login` re-grants it, and
nothing else in this package should hardcode a scope string again.

Real gcloud constraint this module works within (verified against `gcloud
auth login --help` / `gcloud auth application-default login --help`, not
assumed - an earlier version of this module got this wrong):

- `gcloud auth login` has NO --scopes flag. It always uses a fixed scope
  set for the gcloud CLI's own OAuth client, and does not include Analytics
  or Tag Manager scopes. There is no way to add scopes to it.
- `gcloud auth application-default login [ACCOUNT] --scopes=...` DOES
  support custom scopes, but it writes to a single, global, well-known
  Application Default Credentials location - "Any credentials previously
  generated by `gcloud auth application-default login` will be
  overwritten." There is exactly one scoped identity active at a time,
  system-wide, for personal Google accounts.
- Service accounts (`gcloud auth activate-service-account`) are different:
  their tokens aren't limited by a prior OAuth consent, so
  `gcloud auth print-access-token --account=<service-account-email>
  --scopes=...` works and can coexist with other identities. That path
  lives in TelemetryProvider._access_token's `account` parameter, not here.

So for personal accounts, "check/grant scopes for N accounts" cannot mean
"N independently-usable credentials" - it means "make ONE of them the
active ADC identity, with the right scopes, right now." `gtw auth login`
and `gtw accounts discover` are built around that constraint rather than
pretending otherwise.
"""

from __future__ import annotations

import json
import os
import subprocess
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

# Needed to read GA4 report/admin data and GTM containers (pull_from_ga4,
# `gtw query`, `gtw accounts discover`, `gtw wizard`'s status check).
READ_SCOPES: tuple[str, ...] = (
    "https://www.googleapis.com/auth/analytics.readonly",
    "https://www.googleapis.com/auth/tagmanager.readonly",
)

# Needed to create/modify GA4 properties and GTM containers (`gtw
# provision`, `gtw deploy`).
WRITE_SCOPES: tuple[str, ...] = (
    "https://www.googleapis.com/auth/analytics.edit",
    "https://www.googleapis.com/auth/tagmanager.edit.containers",
)

# Always requested alongside the above - identity + general GCP API access.
BASE_SCOPES: tuple[str, ...] = (
    "openid",
    "email",
    "https://www.googleapis.com/auth/cloud-platform",
)

ALL_SCOPES: tuple[str, ...] = BASE_SCOPES + READ_SCOPES + WRITE_SCOPES


def scopes_arg(scopes: tuple[str, ...] = ALL_SCOPES) -> str:
    """Comma-joined scope list, as `gcloud auth application-default login
    --scopes=` expects."""
    return ",".join(scopes)


@dataclass
class AccountScopeStatus:
    """Which account the *current* Application Default Credentials belong
    to, and whether it has the required scopes. `account` is populated from
    the token itself (tokeninfo's `email`), not merely echoed back from a
    request - so a mismatch between what you asked for and what's actually
    active is visible rather than silently assumed."""

    account: str = ""
    granted_scopes: frozenset[str] = field(default_factory=frozenset)
    missing: tuple[str, ...] = ()
    error: str | None = None

    @property
    def ok(self) -> bool:
        return not self.missing and not self.error


def list_gcloud_accounts() -> list[str]:
    """Accounts gcloud knows about via plain `gcloud auth login` (a
    separate credential store from Application Default Credentials - see
    module docstring). Useful to show what's available to pick from, not
    to check scopes against."""
    result = subprocess.run(
        ["gcloud", "auth", "list", "--format=json"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return []
    try:
        entries = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return []
    return [str(e["account"]) for e in entries if e.get("account")]


def _adc_credentials_file() -> str:
    return os.environ.get("GOOGLE_APPLICATION_CREDENTIALS") or str(
        Path.home() / ".config" / "gcloud" / "application_default_credentials.json"
    )


def _adc_identity_label() -> str:
    """Best-effort human-readable identity for the current ADC.

    For a service account, the credentials file itself carries
    `client_email` - service-account tokens never include an `email` field
    via tokeninfo (confirmed against a real service-account token; it
    returns only `issued_to`/`audience`/`scope`), so that's the only
    reliable source for this case. For a personal (authorized_user)
    credential, tokeninfo's `email` field is used instead, via the caller.
    """
    try:
        with open(_adc_credentials_file()) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return ""
    return str(data.get("client_email") or "")


def _tokeninfo_email(token: str) -> str:
    try:
        with urllib.request.urlopen(
            f"https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={token}",
            timeout=10,
        ) as resp:
            info = json.load(resp)
    except (urllib.error.URLError, OSError, json.JSONDecodeError):
        return ""
    return str(info.get("email") or "")


def check_adc_scopes(required: tuple[str, ...] = ALL_SCOPES) -> AccountScopeStatus:
    """Check whether the *current* Application Default Credentials can
    actually be used with `required` scopes, and which account they
    belong to.

    This mints a token scoped to exactly `required` (matching what
    TelemetryProvider._access_token actually requests) rather than
    inspecting a default/unscoped token's granted scopes - a service
    account's *default* token is scoped to bare cloud-platform only, so
    checking that would misreport a perfectly capable service account as
    missing everything else. For a service account, IAM (not a
    pre-consented scope list) governs what it can mint, so "the scoped
    request succeeded" IS the capability check. For a personal account,
    the scoped request only succeeds if those scopes were already granted
    via `gtw auth login`/`gcloud auth application-default login --scopes=`.

    Read-only - never triggers a login. Use this to decide whether
    `ensure_adc_scopes` needs to prompt at all.
    """
    result = subprocess.run(
        [
            "gcloud",
            "auth",
            "application-default",
            "print-access-token",
            f"--scopes={scopes_arg(required)}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    identity = _adc_identity_label()

    if result.returncode == 0 and result.stdout.strip():
        token = result.stdout.strip().splitlines()[0]
        if not identity:
            identity = _tokeninfo_email(token)
        return AccountScopeStatus(account=identity, granted_scopes=frozenset(required))

    if not identity:
        # Fall back to a default (unscoped) token just to identify who's
        # active, for a clearer error message - a personal account missing
        # scopes still has *a* valid default token.
        default = subprocess.run(
            ["gcloud", "auth", "application-default", "print-access-token"],
            capture_output=True,
            text=True,
            check=False,
        )
        if default.returncode == 0 and default.stdout.strip():
            identity = _tokeninfo_email(default.stdout.strip().splitlines()[0])
        else:
            return AccountScopeStatus(error="No Application Default Credentials found.")

    return AccountScopeStatus(
        account=identity, missing=required, error=result.stderr.strip() or None
    )


def ensure_adc_scopes(
    account: str | None = None,
    required: tuple[str, ...] = ALL_SCOPES,
    force: bool = False,
) -> AccountScopeStatus:
    """Idempotent: only runs the interactive `gcloud auth application-default
    login` if the current ADC doesn't already belong to `account` (when
    given) with all `required` scopes - or if `force=True`.

    This is the one command to re-run whenever `ALL_SCOPES` above gains a
    new entry, or to switch which identity is the active ADC. Because ADC
    is a single global credential, running this for a *different* account
    overwrites whichever one was active before - it does not accumulate
    multiple usable identities.
    """
    status = check_adc_scopes(required)
    already_right_identity = account is None or status.account == account
    if status.ok and already_right_identity and not force:
        return status

    login_cmd = ["gcloud", "auth", "application-default", "login"]
    if account:
        login_cmd.append(account)
    login_cmd.append(f"--scopes={scopes_arg(required)}")
    subprocess.run(login_cmd, check=True)
    return check_adc_scopes(required)
